In [3]:
import tensorflow as tf
import numpy as np

In [4]:
print(tf.__version__)

2.19.0


In [5]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#NDim of tensor
scalar.ndim

0

In [7]:
#Creating vector
vec = tf.constant([10, 10])
vec

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vec.ndim

1

In [9]:
#create a matrix
mat = tf.constant([[10,7],[7,10]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
mat.ndim

2

In [11]:
#one more matrix
an_mat = tf.constant([[10.,7.],[12.,54.],[8.,9.]])
an_mat

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [12., 54.],
       [ 8.,  9.]], dtype=float32)>

In [12]:
an_mat.ndim

2

In [13]:
#creating tensor
tensor = tf.constant([[[1,2],[2,3]],[[1,2],[1,2]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3]],

       [[1, 2],
        [1, 2]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
t = tf.Variable([[[16,5],[12,3]],[[11,29],[14,7]]])
t

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int32, numpy=
array([[[16,  5],
        [12,  3]],

       [[11, 29],
        [14,  7]]], dtype=int32)>

In [16]:
t[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16,  5],
       [12,  3]], dtype=int32)>

In [17]:
t[0,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  3], dtype=int32)>

In [18]:
t[0,0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [19]:
t[0,0,1].numpy()

np.int32(5)

In [20]:
t[0, 0, -1].numpy()

np.int32(5)

In [21]:
t[0, 0, 1].assign(99)
t[0, 0].numpy() 

array([16, 99], dtype=int32)

In [22]:
t[0, 1].assign([88, 77])
t[0].numpy()

array([[16, 99],
       [88, 77]], dtype=int32)

In [23]:
#create random tensors

In [24]:
random = tf.random.Generator.from_seed(42)
random = random.normal(shape=(3,2))
random1=tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random , random1, random == random1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [25]:
#Shuffle a tensor
new_ten = tf.constant([[10,7],[3,4],[5,2]])
tf.random.shuffle(new_ten)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  2],
       [10,  7]], dtype=int32)>

In [26]:
tf.random.shuffle(new_ten)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [27]:
tf.random.shuffle(new_ten, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [28]:
tf.random.set_seed(42)#global level seed 
tf.random.shuffle(new_ten, seed=42)#not changning (operational level seed)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  2]], dtype=int32)>

In [29]:
tf.ones([3,5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros(shape=(9,2))

<tf.Tensor: shape=(9, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

**Numpy to Tensorflow**

In [32]:
import numpy as np
numpy_a = np.arange(1,25, dtype = float)
numpy_a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [33]:
a = tf.constant(numpy_a)
a

<tf.Tensor: shape=(24,), dtype=float64, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])>

In [34]:
b=tf.constant(numpy_a, shape=(2,3,4))
b,a

(<tf.Tensor: shape=(2, 3, 4), dtype=float64, numpy=
 array([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],
 
        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])>,
 <tf.Tensor: shape=(24,), dtype=float64, numpy=
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])>)

In [35]:
b.ndim

3

In [36]:
a.ndim

1

**Getting info from tensor**

In [38]:
'''shape, rank(ndim), axis and dimension which already did above 
its like fetching elements from the table of tensors ele and size tf.size(tensor)'''

'shape, rank(ndim), axis and dimension which already did above \nits like fetching elements from the table of tensors ele and size tf.size(tensor)'

In [39]:
tensor_of_rnk4=tf.ones([3,2,5,6])
tensor_of_rnk4

<tf.Tensor: shape=(3, 2, 5, 6), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 

In [40]:
tf.size(tensor_of_rnk4)

<tf.Tensor: shape=(), dtype=int32, numpy=180>

In [41]:
tf.shape(tensor_of_rnk4)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 5, 6], dtype=int32)>

In [42]:
tensor_of_rnk4[0]

<tf.Tensor: shape=(2, 5, 6), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]], dtype=float32)>

In [43]:
tensor_of_rnk4.shape

TensorShape([3, 2, 5, 6])

In [44]:
print("Dtype of tensor:",tensor_of_rnk4.dtype)
print("N_Dim of(rank):", tensor_of_rnk4.ndim)
print("Shape of tensor:",tensor_of_rnk4.shape)
print("ele along the 0 axis:",tensor_of_rnk4.shape[0])
print("ele along the last axis:",tensor_of_rnk4.shape[-1])
print("Total n. of ele in our tensor",tf.size(tensor_of_rnk4).numpy())

Dtype of tensor: <dtype: 'float32'>
N_Dim of(rank): 4
Shape of tensor: (3, 2, 5, 6)
ele along the 0 axis: 3
ele along the last axis: 6
Total n. of ele in our tensor 180


In [45]:
#Tensors can be indexed like python list

In [46]:
#Get the first 2 ele from each direction
tensor_of_rnk4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [47]:
#Get 1st ele from each dim except for the 3rd one
tensor_of_rnk4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 5, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [48]:
rnk2_tensor = tf.constant([[3,2],[2,7]])
rnk2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [2, 7]], dtype=int32)>

In [49]:
rnk2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 7], dtype=int32)>

In [50]:
#Extra dim to rnk2_tensor without changing its prev values
rnk3_tensor = rnk2_tensor[...,tf.newaxis]
rnk3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [2]],

       [[2],
        [7]]], dtype=int32)>

In [51]:
Rnk2 = rnk2_tensor @ rnk2_tensor
Rnk2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 20],
       [20, 53]], dtype=int32)>

In [52]:
Rnkk2 = rnk2_tensor * rnk2_tensor#this is not the right way to do matrix multiplication
Rnkk2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9,  4],
       [ 4, 49]], dtype=int32)>

In [53]:
tf.matmul(Rnkk2,Rnkk2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  97,  232],
       [ 232, 2417]], dtype=int32)>

In [54]:
new_col = tf.constant([[5],[6]])

In [55]:
res = tf.concat([Rnk2, new_col], axis = 1)
res

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 20,  5],
       [20, 53,  6]], dtype=int32)>

In [56]:
tf.reshape(res , shape = (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 20],
       [ 5, 20],
       [53,  6]], dtype=int32)>

In [59]:
tf.transpose(res), tf.reshape(res, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[13, 20],
        [20, 53],
        [ 5,  6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[13, 20,  5],
        [20, 53,  6]], dtype=int32)>)

In [63]:
tf.matmul(tf.transpose(res), Rnkk2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 197, 1032],
       [ 392, 2677],
       [  69,  314]], dtype=int32)>

**The Dot Product**

In [70]:
# performing dot product on res and Rnkk2
tf.tensordot(tf.transpose(res), Rnkk2, axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 197, 1032],
       [ 392, 2677],
       [  69,  314]], dtype=int32)>

### Changing the data type of tensor


In [75]:
A = tf.constant([1.3,1.4,1.5])
A

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.3, 1.4, 1.5], dtype=float32)>

In [77]:
A.dtype

tf.float32

In [83]:
A = tf.cast(A , dtype = tf.float16)
A.dtype

tf.float16

In [87]:
B = tf.cast(A, dtype = tf.int32)
B

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 1, 1], dtype=int32)>

In [91]:
C = tf.cast(B, dtype = tf.int16)
C

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 1, 1], dtype=int16)>

***Aggreagating tensor***

In [96]:
e = tf.constant([[-7,10],[1,3]])
e

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-7, 10],
       [ 1,  3]], dtype=int32)>

In [100]:
a = tf.abs(e)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 1,  3]], dtype=int32)>

In [104]:
#min
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [106]:
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

In [108]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [110]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float64, numpy=300.0>

In [114]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float64, numpy=12.5>

In [146]:
import tensorflow_probability as tfp
x = tf.constant([1.0, 2.0, 3.0, 4.0])
var = tfp.stats.variance(x)
var

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

In [148]:
e = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
variance = tfp.stats.variance(e)
variance

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [160]:
#SD dtype should be float then it will work only
tf.math.reduce_std(a)

<tf.Tensor: shape=(), dtype=float64, numpy=6.922186552431729>

### Postional max and min of tensor

In [165]:
f = tf.random.uniform(shape=[59])
f

<tf.Tensor: shape=(59,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ,
       0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869,
       0.8163481 , 0.65651655, 0.9258256 , 0.2391715 ], dtype=float32)>

In [173]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9869993925094604>

In [171]:
f[47]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9869993925094604>

In [175]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [179]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.013772249221801758>

### Squeezing a tensor(removing all single dim)


In [182]:
g = tf.random.set_seed(53)
g = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[3.8196361e-01, 2.3903239e-01, 9.9752426e-01, 1.8916786e-01,
           5.6714785e-01, 7.8952193e-02, 3.7483108e-01, 9.4712842e-01,
           2.0741844e-01, 3.3790231e-01, 6.6301179e-01, 7.3679757e-01,
           1.8487132e-01, 4.6934474e-01, 3.8190556e-01, 7.1974528e-01,
           9.9162900e-01, 1.7788613e-01, 6.5675914e-01, 6.3827372e-01,
           4.9466026e-01, 2.2245002e-01, 3.5675311e-01, 1.6085386e-01,
           4.2665243e-02, 1.5246308e-01, 2.5725365e-04, 3.7915444e-01,
           2.6980221e-01, 1.6064703e-01, 7.1868837e-01, 4.3204701e-01,
           2.2218227e-01, 3.6847734e-01, 2.7116644e-01, 7.5607693e-01,
           2.1148157e-01, 9.1654277e-01, 4.4660330e-01, 3.2091773e-01,
           2.4330258e-02, 6.2409985e-01, 5.4379940e-01, 7.1591926e-01,
           1.0848081e-01, 9.4688749e-01, 6.3822496e-01, 2.4165857e-01,
           5.5070806e-01, 8.0952215e-01]]]]], dtype=float32)>

In [184]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [188]:
g_squeezed = tf.squeeze(g)
g_squeezed.shape

TensorShape([50])

### One Hot Encode

In [193]:
list = [0,1,2,3]
tf.one_hot(list , depth= 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [195]:
#specigy custom val
tf.one_hot(list, depth = 4, on_value = " hey how are u", off_value = " are you mad")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b' hey how are u', b' are you mad', b' are you mad',
        b' are you mad'],
       [b' are you mad', b' hey how are u', b' are you mad',
        b' are you mad'],
       [b' are you mad', b' are you mad', b' hey how are u',
        b' are you mad'],
       [b' are you mad', b' are you mad', b' are you mad',
        b' hey how are u']], dtype=object)>

### Math Function


In [206]:
h = tf.range(1,10)

In [200]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [212]:
tf.sqrt(tf.cast(h,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [214]:
tf.math.log(tf.cast(h,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

In [219]:
j = tf.constant(np.array([1.,4.,5.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 5.])>

In [221]:
np.array(j), type(np.array(j))

(array([1., 4., 5.]), numpy.ndarray)

In [223]:
j.numpy(),type(j.numpy())

(array([1., 4., 5.]), numpy.ndarray)

In [227]:
j.numpy()[1]

np.float64(4.0)

In [229]:
k = tf.constant(np.array([1.9,7.3,5.2]))
l = tf.constant([3.2,4.3,6.2])
k, l

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1.9, 7.3, 5.2])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.2, 4.3, 6.2], dtype=float32)>)

### CPU & GPU

In [232]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [236]:
tf.config.list_physical_devices("GPU")

[]

In [238]:
!nvidia-smi

Sun Jul 27 01:44:45 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.28                 Driver Version: 576.28         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   33C    P8              3W /   95W |       1MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----